# Generated by Django 2.2.5 on 2020-03-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20200320_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(null=True, upload_to='pokemon_pics', verbose_name='Изображение'),
        ),
    ]
